// Generated by .claude/skills/fetch-and-update/water-bulletin-to-ts.ts from data/water-bulletin/. Do not edit by hand.
// Source: Cyprus Water Development Department, weekly «Δελτίο Νερού» workbooks.

export interface WeeklyBulletin {
  /** Date of the edition (upload date, or the edition date for back issues sent by the WDD). */
  edition: string;
  /** Last day of the week the figures cover, read from the workbook's period label. */
  weekEnding: string;
  /** All 18 main dams over the week, mln. m³. */
  damInflow: number | null;
  damOutflow: number | null;
  /** Average m³ a day over the week, per treatment plant (dam water) and per desalination unit. Absent before June 2026. */
  treatment?: Record<string, number>;
  desalination?: Record<string, number>;
}

export const WEEKLY_BULLETINS: WeeklyBulletin[] = [
  {
    "edition": "2026-02-16",
    "weekEnding": "2026-02-16",
    "damInflow": 11.539,
    "damOutflow": 0.868
  },
  {
    "edition": "2026-02-24",
    "weekEnding": "2026-02-24",
    "damInflow": 8.264,
    "damOutflow": 0.868
  },
  {
    "edition": "2026-03-02",
    "weekEnding": "2026-03-02",
    "damInflow": 2.755,
    "damOutflow": 0.489
  },
  {
    "edition": "2026-03-09",
    "weekEnding": "2026-03-09",
    "damInflow": 1.837,
    "damOutflow": 0.653
  },
  {
    "edition": "2026-03-16",
    "weekEnding": "2026-03-16",
    "damInflow": 2.794,
    "damOutflow": 0.665
  },
  {
    "edition": "2026-03-23",
    "weekEnding": "2026-03-23",
    "damInflow": 15.745,
    "damOutflow": 0.769
  },
  {
    "edition": "2026-03-30",
    "weekEnding": "2026-03-30",
    "damInflow": 12.864,
    "damOutflow": 0.464
  },
  {
    "edition": "2026-04-06",
    "weekEnding": "2026-04-06",
    "damInflow": 8.273,
    "damOutflow": 0.425
  },
  {
    "edition": "2026-04-20",
    "weekEnding": "2026-04-20",
    "damInflow": 4.046,
    "damOutflow": 0.371
  },
  {
    "edition": "2026-04-27",
    "weekEnding": "2026-04-27",
    "damInflow": 3.231,
    "damOutflow": 0.426
  },
  {
    "edition": "2026-05-11",
    "weekEnding": "2026-05-11",
    "damInflow": 5.327,
    "damOutflow": 0.797
  },
  {
    "edition": "2026-05-18",
    "weekEnding": "2026-05-18",
    "damInflow": 2.605,
    "damOutflow": 0.756
  },
  {
    "edition": "2026-06-10",
    "weekEnding": "2026-06-08",
    "damInflow": 1.065,
    "damOutflow": 0.942,
    "treatment": {
      "tersefanou": 25532,
      "kornos": 14984,
      "limassol": 19863,
      "asprokremmos": 16371,
      "kannaviou": 6014
    },
    "desalination": {
      "dhekelia": 54919,
      "vasilikos": 58059,
      "episkopi": 38650,
      "larnaca": 53905,
      "paphos": 20419,
      "moni": 13494,
      "kissonerga": 11786,
      "limassol-port": 10018
    }
  },
  {
    "edition": "2026-07-13",
    "weekEnding": "2026-07-13",
    "damInflow": 0.296,
    "damOutflow": 1.128,
    "treatment": {
      "tersefanou": 30137,
      "kornos": 23040,
      "limassol": 18237,
      "asprokremmos": 17029,
      "kannaviou": 7200
    },
    "desalination": {
      "dhekelia": 55889,
      "vasilikos": 56807,
      "episkopi": 36126,
      "larnaca": 54676,
      "paphos": 20852,
      "moni": 12478,
      "kissonerga": 11078,
      "limassol-port": 8742
    }
  },
  {
    "edition": "2026-07-20",
    "weekEnding": "2026-07-20",
    "damInflow": 0.204,
    "damOutflow": 1.219,
    "treatment": {
      "tersefanou": 29531,
      "kornos": 21321,
      "limassol": 17189,
      "asprokremmos": 18257,
      "kannaviou": 7500
    },
    "desalination": {
      "dhekelia": 56187,
      "vasilikos": 57135,
      "episkopi": 37853,
      "larnaca": 57758,
      "paphos": 20967,
      "moni": 13072,
      "kissonerga": 11139,
      "limassol-port": 9832
    }
  },
  {
    "edition": "2026-07-27",
    "weekEnding": "2026-07-27",
    "damInflow": 0.152,
    "damOutflow": 1.304,
    "treatment": {
      "tersefanou": 32631,
      "kornos": 22116,
      "limassol": 20576,
      "asprokremmos": 19414,
      "kannaviou": 7514
    },
    "desalination": {
      "dhekelia": 55322,
      "vasilikos": 57240,
      "episkopi": 34424,
      "larnaca": 57392,
      "paphos": 20397,
      "moni": 13878,
      "kissonerga": 11124,
      "limassol-port": 9475
    }
  },
  {
    "edition": "2026-09-07",
    "weekEnding": "2026-09-07",
    "damInflow": 0.198,
    "damOutflow": 1.204,
    "treatment": {
      "tersefanou": 28532,
      "kornos": 22760,
      "limassol": 28160,
      "asprokremmos": 20143,
      "kannaviou": 7643
    },
    "desalination": {
      "dhekelia": 54345,
      "vasilikos": 57124,
      "episkopi": 33581,
      "larnaca": 54986,
      "paphos": 20781,
      "moni": 12747,
      "kissonerga": 1047,
      "limassol-port": 8085
    }
  },
  {
    "edition": "2026-09-14",
    "weekEnding": "2026-09-14",
    "damInflow": 0.061,
    "damOutflow": 1.37,
    "treatment": {
      "tersefanou": 31654,
      "kornos": 25857,
      "limassol": 27324,
      "asprokremmos": 20329,
      "kannaviou": 9643
    },
    "desalination": {
      "dhekelia": 54175,
      "vasilikos": 57195,
      "episkopi": 33920,
      "larnaca": 55723,
      "paphos": 20754,
      "moni": 12223,
      "kissonerga": 350,
      "limassol-port": 9026
    }
  }
];
